import { venezuelaStates } from "./venezuelaStates";

const stateLatLngMap = venezuelaStates.reduce<Record<string, [number, number]>>(
  (acc, state) => {
    acc[state.value] = state.latLng as [number, number];
    return acc;
  },
  {}
);

const rawMunicipalitiesByState: Record<string, string[]> = {
  AM: [
    "Alto Orinoco",
    "Atabapo",
    "Atures",
    "Autana",
    "Manapiare",
    "Maroa",
    "Río Negro",
  ],
  AN: [
    "Anaco",
    "Aragua",
    "Bolívar",
    "Bruzual",
    "Cajigal",
    "Carvajal",
    "Diego Bautista Urbaneja",
    "Freites",
    "Guanta",
    "Guanipa",
    "Independencia",
    "Libertad",
    "McGregor",
    "Miranda",
    "Monagas",
    "Peñalver",
    "Píritu",
    "San Juan de Capistrano",
    "Santa Ana",
    "Simón Rodríguez",
    "Sotillo",
  ],
  AP: [
    "Achaguas",
    "Biruaca",
    "Muñoz",
    "Páez",
    "Pedro Camejo",
    "Rómulo Gallegos",
    "San Fernando",
  ],
  AR: [
    "Bolívar",
    "Camatagua",
    "Francisco Linares Alcántara",
    "Girardot",
    "José Ángel Lamas",
    "José Félix Ribas",
    "José Rafael Revenga",
    "Libertador",
    "Mario Briceño Iragorry",
    "Ocumare de la Costa de Oro",
    "San Casimiro",
    "San Sebastián",
    "Santiago Mariño",
    "Santos Michelena",
    "Sucre",
    "Tovar",
    "Urdaneta",
    "Zamora",
  ],
  BA: [
    "Alberto Arvelo Torrealba",
    "Andrés Eloy Blanco",
    "Antonio José de Sucre",
    "Arismendi",
    "Barinas",
    "Bolívar",
    "Cruz Paredes",
    "Ezequiel Zamora",
    "Obispos",
    "Pedraza",
    "Rojas",
    "Sosa",
  ],
  BO: [
    "Angostura",
    "Angostura del Orinoco",
    "Caroní",
    "Cedeño",
    "Padre Pedro Chien",
    "El Callao",
    "Gran Sabana",
    "Piar",
    "Roscio",
    "Sifontes",
    "Sucre",
  ],
  CA: [
    "Bejuma",
    "Carlos Arvelo",
    "Diego Ibarra",
    "Guacara",
    "Juan José Mora",
    "Libertador",
    "Los Guayos",
    "Miranda",
    "Montalbán",
    "Naguanagua",
    "Puerto Cabello",
    "San Diego",
    "San Joaquín",
    "Valencia",
  ],
  CO: [
    "Anzoátegui",
    "Girardot",
    "Lima Blanco",
    "Pao de San Juan Bautista",
    "Ricaurte",
    "Rómulo Gallegos",
    "San Carlos",
    "Tinaco",
    "Tinaquillo",
  ],
  DA: ["Antonio Díaz", "Casacoima", "Pedernales", "Tucupita"],
  FA: [
    "Acosta",
    "Bolívar",
    "Buchivacoa",
    "Carirubana",
    "Colina",
    "Dabajuro",
    "Democracia",
    "Falcón",
    "Federación",
    "Iturriza",
    "Jacura",
    "Los Taques",
    "Manaure",
    "Mauroa",
    "Miranda",
    "Palmasola",
    "Petit",
    "Píritu",
    "San Francisco",
    "Sucre",
    "Silva",
    "Tocópero",
    "Unión",
    "Urumaco",
    "Zamora",
  ],
  GU: [
    "Camaguán",
    "Chaguaramas",
    "El Socorro",
    "Francisco de Miranda",
    "José Félix Ribas",
    "José Tadeo Monagas",
    "Juan Germán Roscio",
    "Juan José Rondón",
    "Julián Mellado",
    "Leonardo Infante",
    "Ortiz",
    "San Gerónimo de Guayabal",
    "San José de Guaribe",
    "Santa María de Ipire",
    "Zaraza",
  ],
  LA: [
    "Andrés Eloy Blanco",
    "Crespo",
    "Iribarren",
    "Jiménez",
    "Morán",
    "Palavecino",
    "Simón Planas",
    "Torres",
    "Urdaneta",
  ],
  ME: [
    "Alberto Adriani",
    "Andrés Bello",
    "Antonio Pinto Salinas",
    "Aricagua",
    "Arzobispo Chacón",
    "Campo Elías",
    "Caracciolo Parra Olmedo",
    "Cardenal Quintero",
    "Guaraque",
    "Julio César Salas",
    "Justo Briceño",
    "Libertador",
    "Miranda",
    "Obispo Ramos de Lora",
    "Padre Noguera",
    "Pueblo Llano",
    "Rangel",
    "Rivas Dávila",
    "Santos Marquina",
    "Sucre",
    "Tovar",
    "Tulio Febres Cordero",
    "Zea",
  ],
  MI: [
    "Acevedo",
    "Andrés Bello",
    "Baruta",
    "Bolívar",
    "Brión",
    "Buroz",
    "Carrizal",
    "Chacao",
    "Cristóbal Rojas",
    "El Hatillo",
    "Guaicaipuro",
    "Gual",
    "Independencia",
    "Lander",
    "Los Salias",
    "Páez",
    "Paz Castillo",
    "Plaza",
    "Sucre",
    "Urdaneta",
    "Zamora",
  ],
  MO: [
    "Acosta",
    "Aguasay",
    "Bolívar",
    "Caripe",
    "Cedeño",
    "Libertador",
    "Maturín",
    "Piar",
    "Punceres",
    "Santa Bárbara",
    "Sotillo",
    "Uracoa",
    "Zamora",
  ],
  NE: [
    "Antolín del Campo",
    "Antonio Díaz",
    "Arismendi",
    "García",
    "Gómez",
    "Macanao",
    "Maneiro",
    "Marcano",
    "Mariño",
    "Tubores",
    "Villalba",
  ],
  PO: [
    "Agua Blanca",
    "Araure",
    "Esteller",
    "Guanare",
    "Guanarito",
    "José Vicente de Unda",
    "Ospino",
    "Páez",
    "Papelón",
    "San Genaro de Boconoíto",
    "San Rafael de Onoto",
    "Santa Rosalía",
    "Sucre",
    "Turén",
  ],
  SU: [
    "Andrés Eloy Blanco",
    "Andrés Mata",
    "Arismendi",
    "Benítez",
    "Bermúdez",
    "Bolívar",
    "Cajigal",
    "Cruz Salmerón Acosta",
    "Libertador",
    "Mariño",
    "Mejía",
    "Montes",
    "Ribero",
    "Sucre",
    "Valdez",
  ],
  TA: [
    "Andrés Bello",
    "Antonio Rómulo Costa",
    "Ayacucho",
    "Bolívar",
    "Cárdenas",
    "Córdoba",
    "Fernández Feo",
    "Francisco de Miranda",
    "García de Hevia",
    "Guásimos",
    "Independencia",
    "Jáuregui",
    "José María Vargas",
    "Junín",
    "Libertad",
    "Libertador",
    "Lobatera",
    "Michelena",
    "Panamericano",
    "Pedro María Ureña",
    "Rafael Urdaneta",
    "Samuel Darío Maldonado",
    "San Cristóbal",
    "San Judas Tadeo",
    "Seboruco",
    "Simón Rodríguez",
    "Sucre",
    "Torbes",
    "Uribante",
  ],
  TR: [
    "Andrés Bello",
    "Boconó",
    "Bolívar",
    "Candelaria",
    "Carache",
    "Carvajal",
    "Campo Elías",
    "Escuque",
    "La Ceiba",
    "Márquez Cañizales",
    "Miranda",
    "Monte Carmelo",
    "Motatán",
    "Pampán",
    "Pampanito",
    "Rangel",
    "Sucre",
    "Trujillo",
    "Urdaneta",
    "Valera",
  ],
  VA: ["Vargas"],
  YA: [
    "Arístides Bastidas",
    "Bolívar",
    "Bruzual",
    "Cocorote",
    "Independencia",
    "José Antonio Páez",
    "La Trinidad",
    "Manuel Monge",
    "Nirgua",
    "Peña",
    "San Felipe",
    "Sucre",
    "Urachiche",
    "Veroes",
  ],
  ZU: [
    "Almirante Padilla",
    "Baralt",
    "Cabimas",
    "Catatumbo",
    "Colón",
    "Francisco Javier Pulgar",
    "Guajira",
    "Jesús Enrique Lossada",
    "Jesús María Semprún",
    "La Cañada de Urdaneta",
    "Lagunillas",
    "Machiques de Perijá",
    "Mara",
    "Maracaibo",
    "Miranda",
    "Rosario de Perijá",
    "San Francisco",
    "Santa Rita",
    "Simón Bolívar",
    "Sucre",
    "Valmore Rodríguez",
  ],
  CC: ["Libertador"],
};

const toValue = (name: string) => {
  return name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toUpperCase();
};

const municipalitiesByState: Record<
  string,
  Array<{ value: string; label: string; latLng: [number, number] }>
> = Object.fromEntries(
  Object.entries(rawMunicipalitiesByState).map(([state, names]) => [
    state,
    names.map((name) => ({
      value: toValue(name),
      label: name,
      latLng: stateLatLngMap[state],
    })),
  ])
);

export const getMunicipalitiesByState = (stateValue: string) => {
  return municipalitiesByState[stateValue] ?? [];
};

export const getDefaultMunicipalityByState = (stateValue: string) => {
  return getMunicipalitiesByState(stateValue)[0] ?? null;
};

export const getMunicipalityByValue = (
  stateValue: string,
  municipalityValue: string
) => {
  return getMunicipalitiesByState(stateValue).find(
    (item) => item.value === municipalityValue
  );
};

export const useVenezuelaMunicipalities = () => {
  return {
    getMunicipalitiesByState,
    getDefaultMunicipalityByState,
    getMunicipalityByValue,
  };
};
